config/routes.rb
Rails.application.routes.draw do
  get  ':username'     => 'users#show'
  get  'home'          => 'users#home'
  get  '/'             => 'users#home'
  post 'users/new'     => 'users#new'
  post 'users/destroy' => 'users#destroy'
  get '*unmatched_route', to: 'users#home'

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  class Mecab
    def initialize
      # DBからng wordを取得
      # ng_word:string, username:string
      @@ng_words = Array.new
      Word.select("ng_word").uniq.each do |ngword|
        @@ng_words << ngword.ng_word
      end
    end

    def filtering(text)
      # 分解
      # オプションはここで渡す, 使う辞書の指定をする
      nm = Natto::MeCab.new(ENV["DICTIONARY_PATH"])
      words = Array.new
      nm.parse(text) do |n|
        words << n.surface
      end

      flag = false # フィルタリングが適応されたかどうか
      filtering_text = String.new

      words.each do |word|
        if @@ng_words.include?(word)
          filtering_text += "＊" * word.size
          flag = true
        else
          filtering_text += word
        end
      end
      return {text: filtering_text, flag: flag}
    end #/def filtering
  end #/calss Mecab


  class TwitterInfo
    def initialize
      @client = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV["CONSUMER_KEY"]
        config.consumer_secret     = ENV["CONSUMER_SECRET"]
        config.access_token        = ENV["ACCESS_TOKEN"]
        config.access_token_secret = ENV["ACCESS_TOKEN_SECRET"]
      end
      # tweetの最後のid
      @@max_id = 0
      # tweet
      @@text = Array.new
    end #/def initialize

    # 戻り値は Hash
    # tweet は Array
    def user_tweet(username)
      # エラー時の試行回数 
      retries = 0
      begin
        # 鍵垢かどうか
        return {err: "鍵が付いているアカウントです"} if @client.user(username).protected

        @name = @client.user(username).name
        if @@max_id == 0
          all_info = @client.user_timeline(username, {count: 100})
        else
          all_info = @client.user_timeline(username, {count: 100, max_id: @@max_id})
        end
      rescue Twitter::Error::TooManyRequests => error
        raise if retries >= 5
        retries += 1
        sleep error.rate_limit.reset_in
        retry
      rescue
        return {err: "存在していないアカウントか何らかのエラーが発生しました"}
      end

      all_info.each do |user_info|
        # 重複するツイートを削除するため
        next if @@max_id == user_info.id
        @@max_id    = user_info.id
        time        = "#{user_info.created_at.strftime("%Y/%m/%d %X")}".strip
        flag        = false #flagはフィルタリングが適応されたかどうか
        tweet       = "#{user_info.text}".strip
        text        = String.new
        reply_users = Array.new

        ## 半角スペースが省略される問題の解決
        ## テキストにユーザ名が含まれているのを分割(ィルタリング対象にしない)
        tweet = tweet.split
        tweet.each do |t|
          if t.match(/^@/)
            reply_users << "#{t} "
          else
            tmp        = Mecab.new.filtering(t) # {text: , flag: }
            text += tmp[:text]
            flag = true if tmp[:flag]
          end
        end
        @@text << {text: text, reply_users: reply_users, time: time, flag: flag}
      end
      # @userの中身 {name: ***, err: ***, tweet:[{text: ***, reply_users: ***, time: ***, flag: ***},{text: ***, reply_users: ***, time: **    *, flag: ***}...]}
      return {name: @name, tweet: @@text}
    end
  end #/class TwitterInfo



  def home
    # DBからng wordを取得
    # ng_word:string, username:string
    @ng_words = Array.new
    Word.select("ng_word").uniq.each do |ngword|
      @ng_words << ngword.ng_word
    end
    @input = Word.new
  end

  def show
    @user  = Hash.new
    client = TwitterInfo.new()

    # DBからng wordを取得
    # ng_word:string, username:string
    @ng_words = Array.new
    Word.select("ng_word").uniq.each do |ngword|
      @ng_words << ngword.ng_word
    end

    # 非同期に処理ができない(わからない)ためとりあえず100ツイートのみで
    1.times do
      # 配列をわたす
      @user = client.user_tweet(params[:username])
    end
    @user[:username] = params[:username]
    @input = Word.new
  end

  def new
    @input = Word.new
    if params[:word][:ng_word] != ""
      @input[:ng_word] = params[:word][:ng_word]
      # すでに登録されているかどうか
      unless Word.exists?(ng_word: @input[:ng_word])
        if @input.save
          render :text => "#{@input[:ng_word]}を登録しました"
        else
          render :text => "エラーが発生しました"
        end

      else
        render :text => "#{@input[:ng_word]}はすでに登録されています"
      end

    else
      render :text => "空白は登録できません"
    end
  end

  def destroy
    @input = Word.destroy_all(ng_word: params[:ng_word])
    render :text => "#{params[:ng_word]}をフィルタリング対象から削除しました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilteringTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/home.html.erb
<body>
  <div class="container"> <!-- container で全体を囲む -->
    <h1>Filtering Twitter</h1>
    <br>
    <div class="row"> <!-- row で列を作る -->

      <%# left %>
      <div class="col-md-8">
        <div>
          <h3>サイトについて</h3>
          フィルタリングを通してTwitterユーザのツイートを見ることができる。
        </div>
        <br>
        <div>
          <h3>使い方</h3>
          <h4>filtering_twitter.taroooyan.com/ユーザ名 <br>
            例） filtering_twitter.taroooyan.com/taroooyan
          </h4>
          にアクセスすることでそのユーザのツイートを見ることができる。<br>
          フィルタリング対象の文字列は＊＊に置換される<br>
          フィルタリング対象対象となったツイートはオレンジ色で表示される<br>
          <br>
          フィルタリング対象とする文字列はテキストボックスに入力することで追加できる。<br>
          フィルタリング対象から外す場合には削除ボタンを押す。
          更新後はリロードしてください
        </div>
      </div>

      <%# right %>
      <div class="col-md-4">
        <h3>現在のフィルタリング文字列</h3>
        <% @ng_words.each do |w| %>
          <div style="margin: -10px 0;">
            <hr>
            <div style="display: inline-block; _display: inline;">
              <%= w.to_s %>
            </div>
            <div style="margin-left: 5px; display: inline-block; _display: inline;">
              <%= button_to "削除", users_destroy_path(:ng_word => w) %>
            </div>
          </div>
        <% end %>
        <hr>

        <div>
          <%= form_for @input, url: users_new_path do |f| %>
            <%= f.text_field :ng_word %>
            <%= f.submit '追加'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<body>
  <div class="container" > <!-- container で全体を囲む -->
    <h1>Filtering Twitter</h1>
    <br>
    <div class="row"> <!-- row で列を作る -->

      <%# left %>
      <div class="col-md-8">
        <div class="container">
          <div class="row">
            <img src="http://www.paper-glasses.com/api/twipi/<%= @user[:username]%>" alt="icon" class="img-thumbnail" >
            <h3><%= "#{@user[:name]}@#{@user[:username]}" %></h3>
            <div class="col-md-1">
            </div>

            <div class="col-md-6">
              <hr>
              <%# @userの中身{name: ***, err: ***, tweet:[{text: ***, reply_users: ***, time: ***, flag: ***},
              {text: ***, reply_users: ***, time: ***, flag: ***}...]} %>
              <% if @user[:err] != nil%>
                <h2> 
                  <%= @user[:err] %>
                </h2>
              <% else %>
                <% @user[:tweet].each do |tweet| %>
                  <div style="padding: 10px 10px; background-color: #F5FFFA;">
                    <span style="color: #4169E1; margin-left: 5px; display: inline-block; _display: inline;">
                      <% tweet[:reply_users].each do |reply_u| %>
                        <%= reply_u.to_s %>
                      <% end %>
                    </span>
                    <% if tweet[:flag] %>
                      <span style="color: #FF8C00;"> <%= tweet[:text].to_s %> </span>
                    <% else %>
                      <%= tweet[:text].to_s %>
                    <% end %>
                    <span style="color: #C0C0C0;"> <%= tweet[:time].to_s %> </span>
                    <hr>
                  </div>
                <% end %>
              <% end %>
            </div>

            <div class="col-md-1">
            </div>
          </div>
        </div>
      </div>

      <%# right %>
      <div class="col-md-4">
        <h3>現在のフィルタリング文字列</h3>
        <% @ng_words.each do |w| %>
          <div style="margin: -10px 0;">
            <hr>
            <div style="display: inline-block; _display: inline;">
              <%= w.to_s %>
            </div>
            <div style="margin-left: 5px; display: inline-block; _display: inline;">
              <%= button_to "削除", users_destroy_path(:ng_word => w) %>
            </div>
          </div>
        <% end %>
        <hr>
        <div>
          <%= form_for @input, url: users_new_path do |f| %>
            <%= f.text_field :ng_word %>
            <%= f.submit '追加'%>
          <% end %>
        </div>
      </div>
    </div>
  </body>